### PR TITLE
Update setup.cfg

### PR DESCRIPTION
**Pull request by avalentino**
Install resources (XML schema files)

### CODE REVIEW

**Comment by alexamici** [comment]
@avalentino thank you for your contibution.

I'm a bit surprised by the proposed change.

Do you say that resources are not installed without this PR? If this is the case I need to understand how I didn't notice any failure.

**Comment by avalentino** [comment]
Hi @alexamici I notice the problem when I was preparing the Debian package for xarray-sentinel (see also [1] and [2]).
The debian tools that build the SW and generate the package are quite complex and the entire procedure that leads to the error is hard to replicate.

A very simplified version of the procedure to reproduce the issue is the following:

```sh
wget https://github.com/bopen/xarray-sentinel/archive/refs/tags/v0.9.3.tar.gz
env SETUPTOOLS_SCM_PRETEND_VERSION=0.9.3 python3 -m pip install xarray-sentinel-0.9.3.tar.gz
```

I admit that the procedure is quite uncommon and it is something that should not happen to a normal user.
The fix, anyway, is really simple so I would appreciate if you could consider to include it.


[1] https://tracker.debian.org/pkg/xarray-sentinel
[2] https://salsa.debian.org/debian-gis-team/xarray-sentinel

**Comment by alexamici** [comment]
1. This is a bit annoying as I hoped using _setuptools_scm_ would make this redundant configs go away
2. Anyway, I agree it is a small price to get the package into Debian 😍

**Comment by avalentino** [comment]
Thank you @alexamici

**Pull request merged**
